# Generated by Django 5.2 on 2025-04-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Electronics', 'ELECTRONICS'), ('Clothing', 'CLOTHING'), ('Books', 'BOOKS')], max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images')),
            ],
        ),
    ]
