# Generated by Django 5.2 on 2025-04-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_code',
        ),
    ]
